import os

MYSQL_HOST = os.environ['OPENSHIFT_MYSQL_DB_HOST']
MYSQL_PORT = os.environ['OPENSHIFT_MYSQL_DB_PORT']

MYSQL_USER = os.environ['OPENSHIFT_MYSQL_DB_USERNAME']
MYSQL_PASS = os.environ['OPENSHIFT_MYSQL_DB_PASSWORD']

MYSQL_DB = 'taobb'
